version: '3'
services:
  server:
    build:
      context: .
    ports:
      - "5002:5002"
      - "6002:6002"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    command: ["python3", "main.py"]

  client:
    build:
      context: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    depends_on:
      - server
    command: ["python3", "main.py"]
